# Generated by Django 5.1.1 on 2024-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='user/images')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
